[package]
name = "idat-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbc = "0.1.2"
des = "0.8.1"
ecb = "0.1.2"
num_enum = "0.7.2"
thiserror = "1.0.61"
